<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Mail;
use App\Newsletter;

class WeeklyUpdate extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'weekly:update';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'This Command is Use for autogenerated mails.';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $user = Newsletter::all();
        foreach ($user as $a)
        {
            Mail::raw("We have new offers for you from E-shopper. Please visit our website", function($message) use ($a)
         {
             $message->from('anitabherde10@gmail.com');
             $message->to($a->user_email)->subject('Weekly Update from E-com Web');
         });

        }
        $this->info('Weekly Update has been send successfully');
        
    }
}
